INSERT INTO test.Todo (content) VALUES ('Fed the cat');
INSERT INTO test.Todo (content) VALUES ('Go for a work');
INSERT INTO test.Todo (content) VALUES ('Buy the ticket');
INSERT INTO test.Todo (content) VALUES ('One more todo');
INSERT INTO test.Todo (content) VALUES ('One more todo 2');
INSERT INTO test.Todo (content) VALUES ('Fed the cat 2');
INSERT INTO test.Todo (content) VALUES ('Go for a work 2');
INSERT INTO test.Todo (content) VALUES ('Buy the ticket 2');
INSERT INTO test.Todo (content) VALUES ('One more todo 3');
INSERT INTO test.Todo (content) VALUES ('One more todo 4');
INSERT INTO test.Todo (content) VALUES ('1');
INSERT INTO test.Todo (content) VALUES ('2');
INSERT INTO test.Todo (content) VALUES ('3');
INSERT INTO test.Todo (content) VALUES ('4');
INSERT INTO test.Todo (content) VALUES ('5');
INSERT INTO test.Todo (content) VALUES ('6');
INSERT INTO test.Todo (content) VALUES ('7');
INSERT INTO test.Todo (content) VALUES ('8');
INSERT INTO test.Todo (content) VALUES ('9');
INSERT INTO test.Todo (content) VALUES ('10');